### ISSUE TITLE
LogicX() gets multidimensional array for arguments

### ISSUE THREAD

**Issue by antonymous** [Happyr/Doctrine-Specification#120]
After 6ea70f5e0fb54c41537e47834c9d889b9a146e38 the chain of calls `Spec::andX/orX()` → `new AndX/OrX()` → `new LogicX()` ends with `LogicX`'s arguments being a multidimensional array, which leads to failing `$child instanceof Filter/QueryModifier` checks. For instance, in the following example `orX` part is completely ignored:
```
$specs = new AndX(
    Spec::orX(
        Spec::eq('field1', 42),
        Spec::eq('field2', 42), 
    ),
    Spec::eq('field3', 42)
);
```
Of cause replacing `Spec::orX()` with `new OrX()` fixes the issue. But is it intended behaviour?
P.S. Thanks for the lib, BTW!

**Comment by Nyholm** [comment]
Thank you for reporting this bug. This is not the intended behavior at all.
I made https://github.com/Happyr/Doctrine-Specification/commit/6ea70f5e0fb54c41537e47834c9d889b9a146e38 because I wanted to make sure one could use the `AndX::andX` function. 

I've made a fix to this issue by using reflection. (https://github.com/Nyholm/Doctrine-Specification/tree/issue120) 
What do you think about that?

**Comment by antonymous** [comment]
I can't imagine a better solution anyway, so... Thanks again.
